### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by robertiagar** [Solocast/solocast-clients#10]
Use Bing search to search for feed types.

http://datamarket.azure.com/dataset/bing/search

Either Bing, or the Google Web Api

**Comment by jeromechrist** [comment]
@robertiagar do you have any pointer for this ? i'm trying to follow some links, everything is deprecated 👻 

This allow a user to search for 'monstercat' and somehow the API returns to you the feed URI ? or the monstercat home page and you have to parse the response to search for the URI ?

**Comment by jeromechrist** [comment]
Should have searched a bit more :blush:

https://www.microsoft.com/cognitive-services/en-us/bing-web-search-api/documentation

looks like a good place to start

**Comment by robertiagar** [comment]
As far as I know both google and bing support to search for a specific thing: links, feeds, images, etc. When this issue was created that was the documentation that i got. 

If what you found works, then using bing is good for now :)

Sorry for the deprecated info on this issue.

Keep in mind that this will require UI changes also. Can you manage it?

**Comment by robertiagar** [comment]
http://stackoverflow.com/questions/39677080/equivalent-of-webfiletype-in-v5-bing-search-api

this does not look good... apparently bing doesn't support this anymore... i will look for an alternative if this is not going to work anymore...

**Comment by robertiagar** [comment]
Closed by #29
